-- Set offset to earliest
SET 'auto.offset.reset'='earliest';

-- Create RAW table
CREATE TABLE TBL_K8_DEMO_0010 (
	ROWKEY VARCHAR PRIMARY KEY
	,NAME VARCHAR
	,SEX VARCHAR
	,ADDRESS VARCHAR
	,MAIL VARCHAR
	,BIRTHDATE VARCHAR
	)
	WITH (
			KAFKA_TOPIC = 'kafka.ksql.headless.demo'
			,VALUE_FORMAT = 'JSON'
			,REPLICAS = 1
			,PARTITIONS = 1
			);

-- Apply transformation
CREATE TABLE TBL_K8_DEMO_0020 AS
SELECT ROWKEY AS USERNAME
	,UCASE(NAME) AS NAME
	,CASE
		WHEN SEX = 'M'
			THEN 'MALE'
		WHEN SEX = 'F'
			THEN 'FEMALE'
		ELSE 'OTHERS'
		END AS SEX
	,LCASE(MAIL) AS MAIL
	,BIRTHDATE
FROM TBL_K8_DEMO_0010 EMIT CHANGES;